### PR TITLE
Corrected bitstring specificier int32 and updated deps

### LINKED ISSUE #157: bitstring specifier warning on int32 (Elixir 1.15.0-rc.0)
Getting a new error while testing this library on elixir 1.15.0-rc.0

```
warning: bitstring specifier "int32" does not exist and is being expanded to "int32()", please use parentheses to remove the ambiguity
  (<redacted>) <redacted>/deps/geo_postgis/lib/geo_postgis/extension.ex:77: <REDACTED>.PostgresTypes."Elixir.Geo.PostGIS.Extension"/1

warning: bitstring specifier "int32" does not exist and is being expanded to "int32()", please use parentheses to remove the ambiguity
  (<redacted>) <redacted>/deps/geo_postgis/lib/geo_postgis/extension.ex:90: <REDACTED>.PostgresTypes."Elixir.Geo.PostGIS.Extension"/6

warning: bitstring specifier "int32" does not exist and is being expanded to "int32()", please use parentheses to remove the ambiguity
  (<redacted>) <redacted>/deps/geo_postgis/lib/geo_postgis/extension.ex:90: <REDACTED>.PostgresTypes."Elixir.Geo.PostGIS.Extension"/2

warning: bitstring specifier "int32" does not exist and is being expanded to "int32()", please use parentheses to remove the ambiguity
  (<redacted>) <redacted>/deps/geo_postgis/lib/geo_postgis/extension.ex:90: <REDACTED>.PostgresTypes."Elixir.Geo.PostGIS.Extension"/3

warning: bitstring specifier "int32" does not exist and is being expanded to "int32()", please use parentheses to remove the ambiguity
  (<redacted>) <redacted>/deps/geo_postgis/lib/geo_postgis/extension.ex:90: <REDACTED>.PostgresTypes."Elixir.Geo.PostGIS.Extension"/5
```

I assume that needs to be replaced with `integer-size(32)` or follow the warning's advice, but based off the docs: https://hexdocs.pm/elixir/1.14/Kernel.SpecialForms.html#%3C%3C%3E%3E/1-unit-and-size (yes I know that this is 1.14, 1.15 isn't officially released as of this writing)

There is no such thing as `int32` as far as bitstring types are concerned

EDIT: In the process of correcting it on local, it appears postgrex used to reference int32 as well, so it may have been a type present in older elixir versions, I don't feel like chasing that down right now however.

### PR DESCRIPTION
**Pull request by IceDragon200**
Sorry about doing all of that inside the same PR, but it was necessary for testing.

I've also updated the config files to match the current standard (i.e. `Config` vs `Mix.Config`)

## Related

* Closes #157

### CODE REVIEW

**Comment by benregn** [comment]
@bryanjos is there any possibility getting this merged and released?

**Comment by bryanjos** [comment]
Hey @benregn thanks! Merging now and will publish update soon

**Comment by bryanjos** [comment]
https://hex.pm/packages/geo_postgis/3.4.3

**Comment by benregn** [comment]
Thank you ❤️

**Pull request merged**
